sudo: required
dist: bionic
language: java
jdk: openjdk8
jobs:
  include:
    - name: oap-shuffle-remote-shuffle
      install:
      - #empty install step
      script:
      - cd ${TRAVIS_BUILD_DIR}/oap-shuffle/remote-shuffle/
      - mvn -q test
