site_name: Remote Shuffle
theme: null
extra_css: [extra.css]
theme_dir: mkdocs_windmill
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/oap-project/remote-shuffle'
extra:
    version: master
    article_nav_top: false
    article_nav_bottom: false



pages:
  - Overview: index.md
  - OAP Installation Guide: OAP-Installation-Guide.md
  - OAP Developer Guide: OAP-Developer-Guide.md




